version: '3.8'
services:
  consumer:
    build:
      dockerfile: consumer.dockerfile
    environment:
      KAFKA_SERVER: "kafka:9092"
      LA_CONFIG_URL: "http://php-apache/LiveAgent/server/public/api/internal"
      LA_URL: "http://php-apache/LiveAgent/server/public/api/internal"
#       LA_URL: "http://{account}.php-apache/LiveAgent/server/public/api/internal"
      LA_KEY: "/app/kafka.key"
    ports:
      - "8082:80"
    networks:
      - front_qu
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./consumer:/app
      - ./dev.kafka.key:/app/kafka.key
networks:
  front_qu:
    external: true
    name: shared