version: '3.8'
services:
  consumer:
    build:
      dockerfile: consumer.dockerfile
    environment:
      KAFKA_SERVER: "kafka:9092"
      LA_URL: "http://php-apache/LiveAgent/server/public/api/internal"
    ports:
      - "8082:80"
    networks:
      - front_qu
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./consumer:/app
networks:
  front_qu:
    external: true
    name: shared