version: '3.8'
services:
  producer:
    build:
      dockerfile: producer.dockerfile
    environment:
      kafka_url: "kafka:9092"
    ports:
      - "8082:80"
    networks:
      - front_qu
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - producer.py:producer.py
      - /home/martin/IdeaProjects/LiveAgent-InternalAPI/build/generate-resources/python:/home/martin/IdeaProjects/LiveAgent-InternalAPI/build/generate-resources/python
networks:
  front_qu:
    external: true
    name: shared