name: Unit tests
on:
  push
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - run: docker network create shared
      - run: docker-compose run -w /app consumer python -m unittest tests/*.py
